### ISSUE TITLE
Multiple flashes within the same browser session hang

### ISSUE THREAD

**Issue by kristiankielhofner** [toverainc/willow-web-flash#3]
Users should be able to use the web flasher for any number of devices they want to connect by just clicking flash over and over. Currently this hangs if you use a different serial port for them, for example. You need to close the tab and revisit the web flasher.

This isn't a good experience for initial user onboarding when they have multiple Willow devices.

**Comment by stintel** [comment]
Actually I can hang the browser tab by just switching between different device types. I see some errors in browser console, will try if fixing those fixes the hang.
