### ISSUE TITLE
Web flash to update now doesnt work 

### ISSUE THREAD

**Issue by SamJongenelen** [toverainc/willow-web-flash#6]
Hey,

Previously i succesfully flashed my s3 box using the utils.sh

Ive used the web flasher (https://flash.heywillow.io/) today succesfully. However i get no logs after the flash and the device doesnt boot. Can reflash using different Baud but didnt work either.

Erase flash didnt help - any tips or did i miss something?

**Comment by stintel** [comment]
Please try https://feature-serial-output.willow-web-flash.pages.dev

**Comment by SamJongenelen** [comment]
Wow this page even showed me a cool esp32 s3 box 3 has been created, with more sensors... wow :)

**Comment by SamJongenelen** [comment]
Ok. I tried this version, but it also doesnt work for me. I've noticed this page also doesnt serve the RC1 firmware (released yesterday).

**Comment by SamJongenelen** [comment]
So, after flashing this version i get logs from the device. Could it be the (tovera hosted) WAS server i use is no longer valid? 

![image](https://github.com/toverainc/willow-web-flash/assets/3382443/eac510c1-d2e0-4219-8d20-335669eb328b)

Anyway, now that I've got logs I can progress. Lets see if I can host the WIS on my notebook

**Comment by stintel** [comment]
You need to run [WAS](https://heywillow.io/components/willow-application-server/) and point the WAS URL to it. You pointed it to WIS.

If you don't see rc.1, you need to select the correct device type. 0.1.0 will not support the new Box-3, but the upcoming version of Web Flash defaults to Box-3, as the Box is EOL and we don't recommend the Lite.

**Comment by kristiankielhofner** [comment]
We should leave this issue open and do some bare-minimum string parsing on the provided WAS url to make sure it's at least in the expected WAS format.

**Comment by SamJongenelen** [comment]
Hey thanks people. My biggest mistake was not learning how to read. This morning i definitely saw it is WAS not WIS.

Uitslag.sh build does give error when no WAS setup, its al pretty straightforward actually, great addition that WAS!
